<?php
require_once("config/config.php");
require_once("config/db.php");
require_once root('includes/header.php');
?>

<div class="container-fluid bg-info" style="height:20vh">
  <div class="row px-5">
    <div class="col-sm-12">
      <h1 class="p-5 text-white ">About Us</h1>
    </div>

    <div class="row d-flex justify-content-center">
      <div class="col-sm-10">
        <div class="card card-body">
          <p class="text-justify" style="font-size: 1.2rem;">
            Digital Assignment is a software that helps the teachers to schedule tasks and assign them to the respective students. Authorized teacher can get the benefits of creating assignments with ease and also they can provide the necessary feedbacks to the students and can provide marking to the students. Additionally, deadlines are provided to the students, and after the submission, they are evaluated by the teachers.The feedbacks generated by the teacher can be viewed by the students.
          </p>
        </div>
      </div>
    </div>
<div class="container">

  <div class="row my-5">
    <div class="col-sm-10 ml-5">
      <h2>Why digital Assignment?</h2>
      <p class="text-justify" style="font-size: 1.2rem;">
      Digital Assignment is one of the fundamental activities in education. In traditional assignment management schemes, assignments are recorded on paper, floppy disks, and emails. They have to be delivered or organized manually. This is inconvenient and inefficient, and may cause many problems due to material limits and human errors, such as disordered printouts (without page numbers), damaged floppy disks, etc. Furthermore, instructors and students usually are unaware of the ongoing academic information, which can be used to help them find out problems and improve their teaching and learning qualities. Therefore, it becomes important to implement an assignment management method, which can provide both instructors and students with quality educational services. 
        
      </p>
    </div>
  </div>
</div>

  </div>
  <?php
  require_once root('includes/footer.php');
  ?>